//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaEngine;

public class LuaEngine_InjectTypeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(LuaEngine.InjectType));
		L.RegVar("None", get_None, null);
		L.RegVar("After", get_After, null);
		L.RegVar("Before", get_Before, null);
		L.RegVar("Replace", get_Replace, null);
		L.RegVar("ReplaceWithPreInvokeBase", get_ReplaceWithPreInvokeBase, null);
		L.RegVar("ReplaceWithPostInvokeBase", get_ReplaceWithPostInvokeBase, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<LuaEngine.InjectType>.Check = CheckType;
		StackTraits<LuaEngine.InjectType>.Push = Push;
	}

	static void Push(IntPtr L, LuaEngine.InjectType arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(LuaEngine.InjectType), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, LuaEngine.InjectType.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_After(IntPtr L)
	{
		ToLua.Push(L, LuaEngine.InjectType.After);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Before(IntPtr L)
	{
		ToLua.Push(L, LuaEngine.InjectType.Before);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Replace(IntPtr L)
	{
		ToLua.Push(L, LuaEngine.InjectType.Replace);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReplaceWithPreInvokeBase(IntPtr L)
	{
		ToLua.Push(L, LuaEngine.InjectType.ReplaceWithPreInvokeBase);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReplaceWithPostInvokeBase(IntPtr L)
	{
		ToLua.Push(L, LuaEngine.InjectType.ReplaceWithPostInvokeBase);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		LuaEngine.InjectType o = (LuaEngine.InjectType)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

